#!/bin/bash
cd ${0%/*} || exit 1	# run from this directory

# remove log files
rm log* > /dev/null 2>&1

# remove dependency files
./Allwclean

# remove binary files
rm $FOAM_USER_APPBIN/customLibraries > /dev/null 2>&1

# remove library files
rm $FOAM_USER_LIBBIN/libabcLibrary.so > /dev/null 2>&1

# clean case files
./case/Allclean
