#!/bin/bash
cd ${0%/*} || exit 1	# run from this directory

# remove log files
rm log* > /dev/null 2>&1

# remove dependency files
wclean app > /dev/null 2>&1

# remove binary files
rm $FOAM_USER_APPBIN/basicIO > /dev/null 2>&1

# clean case files
./case/Allclean
