#!/bin/sh

#SBATCH --ntasks=2
#SBATCH --time=03:00:00
#SBATCH --mem-per-cpu=0
#SBATCH --job-name=mpiTest
#SBATCH --output=job-2-core-%J.out
#SBATCH --account=def-account

cd $FOAM_RUN/mpiTest/damBreak4phaseFine/

blockMesh
setFields
decomposePar
mpirun -n 2 multiphaseEulerFoam -parallel

#------------------------------------------------------------------------------
