#!/bin/bash

./Allwmake

case/Allrun.mesh > log.mesh 2>&1

cp -r case/0.orig case/0

potentialFoam -case case > log.potentialFoam 2>&1

decomposePar -case case > log.decomposePar 2>&1

echo "Finished preparing, running the solver."

mpirun -np 4 simpleFoam -parallel -case case > log.run 2>&1

reconstructPar -case case > log.reconstruct 2>&1

echo "Done."


