#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove copy of 0.org
rm -rf 0

cleanCase

# ----------------------------------------------------------------- end-of-file
