#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Generate the base block mesh and refine
./Allmesh

# Run the solver in parallel
runApplication `getApplication`

# ----------------------------------------------------------------- end-of-file
